Feature lesson15
dymont78/TMS-SalesForces pull request #1
Opened 2021-06-01 16:33 UTC by dymont78

2021-06-03 19:04 UTC, vchesnakoutest requested changes
after fix please send to review again

2021-06-03 19:04 UTC, vchesnakoutest commented on pom.xml
> +            <version>4.0.0-beta-3</version>
советую выносить в properties

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/elements/Button.java
> +
пустая строка , лучше удалить

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/elements/Button.java
> +    public void clickButton(){
отступ перед объявлением метода

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/elements/DropDown.java
> +
пустые строки

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/elements/DropDown.java
> +
п.с.

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/pages/AccountListPage.java
> +    private static final  String URL = "https://oaojzs.lightning.force.com/lightning/o/Account/list?filterName=Recent";
лишний пробел перед String

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/pages/AccountListPage.java
> +    public AccountListPage(WebDriver driver) {
добавить отступ

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/pages/BasePage.java
> +
отступ

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/pages/NewAccountModalPage.java
> +    private static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
RANDOM_STRING

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/pages/NewAccountModalPage.java
> +    private static final  String URL = "https://oaojzs.lightning.force.com/lightning/o/Account/new";
1.пробел лишний
2.лучше вынести https://oaojzs.lightning.force.com/ в общую константу и её поместить в BasePage либо в интерфейс.

BASE_URL + "/lightning/o/Account/new"

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/pages/NewAccountModalPage.java
> +        if (driver.findElement(By.xpath(DUPLICATION_ALERT)).isEnabled()) {
отсуп

2021-06-03 19:04 UTC, vchesnakoutest commented on src/main/java/pages/NewAccountModalPage.java
> +    }
советую выносить в класс с утилитами

2021-06-03 19:04 UTC, vchesnakoutest commented on src/test/java/AccountTest.java
> +        Assert.assertEquals(driver.findElement(By.xpath(String.format(ASSERT_XPATH, "Account Name"))).getText(), accountName);
newAccountModalPage.getAccountName("Account Name"))

2021-06-03 19:04 UTC, vchesnakoutest commented on src/test/java/AccountTest.java
> +    private static final String ASSERT_XPATH = "//span[text() = '%s']/ancestor::div[contains(@class, 'slds-form-element')]//*[contains(@slot, 'outputField')]";
вынести на страницы

2021-06-09 19:37 UTC, vchesnakoutest requested changes
please make fixes and send to review again

2021-06-09 19:37 UTC, vchesnakoutest commented on src/main/java/pages/BasePage.java
> +    public static final String PASSWORD = "&YP39TJUrqxy!Mp*";
логины и пароли - это тестовые данные, они должны находится в тестовых классах.

2021-06-09 19:37 UTC, vchesnakoutest commented on src/test/java/AccountTest.java
>          driver.findElement(By.id("Login")).click();
для логина необходимо сделать отдельный метод на странице и уже в него передавать тестовые данные (логин, пароль и тд)

2021-06-09 19:37 UTC, vchesnakoutest commented on src/main/java/pages/BasePage.java
> +    public WebElement findByXpath(String textLabel) {
по твоему коду этот метод должен находится в NewAccountModalPage. Локатор ASSERT_XPATH тоже туда же.

2021-06-10 05:42 UTC, dymont78 commented on src/main/java/pages/BasePage.java
> +    public WebElement findByXpath(String textLabel) {
Ну да, не понял как так получилось..

2021-06-10 07:46 UTC, dymont78 commented on src/main/java/pages/BasePage.java
> +    public static final String PASSWORD = "&YP39TJUrqxy!Mp*";
Исправил

2021-06-10 07:46 UTC, dymont78 commented on src/test/java/AccountTest.java
>          driver.findElement(By.id("Login")).click();
Сделал

2021-06-11 15:01 UTC, vchesnakoutest approved these changes
please merge

2021-06-12 11:38 UTC, merged